title: 技術屋メモ
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: minimal-mistakes-jekyll
#remote_theme: "mmistakes/minimal-mistakes"
#google_analytics: G-YD4B1NB2TP
#header_pages:
#  - policy.md

#theme: minimal-mistakes-jekyll
#minimal_mistakes_skin: dark
#locale: ja-JP

#theme: minima
#remote_theme: vsoch/docsy-jekyll