title: 技術屋メモ
remote_theme           : "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
#google_analytics: G-YD4B1NB2TP
#header_pages:
#  - policy.md

#theme: minimal-mistakes-jekyll
#minimal_mistakes_skin: dark
#locale: ja-JP

#theme: minima
#remote_theme: vsoch/docsy-jekyll